hostconfig:
  dns: 172.16.10.1
  tod: ntp.ubuntu.com # NTP Server
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "gkeonprem.local"
blocks:
  - netmask: 255.255.255.0 
    gateway: 10.0.10.1 # DFGW for nodes
    ips:
    - ip: 10.0.10.101 # User Cluster node 1
      hostname: user-host1   # will be trimmed to host6
    - ip: 10.0.10.102 # User Cluster node 2
      hostname: user-host2   # will be trimmed to host7
    - ip: 10.0.10.103 #User Cluster node 3
      hostname: user-host3   # will be trimmed to host8
